# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bestSubset <- function(item_representations, ratings, n) {
    .Call('_rDppDiversity_bestSubset', PACKAGE = 'rDppDiversity', item_representations, ratings, n)
}

