# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' DPP Subset Searching Algorithm For R
#'
#' @param item_representations Matrix
#' @param ratings Matrix
#' @param n int
#'
#' @return DataFrame with two columns id and gain
#' @export
#'
#' @examples
#' library(rDppDiversity)
#' bestSubset(matrix(c(-0.1, -0.15, 0.2, 0.3, -0.2, -0.3), nrow=3, ncol=2, byrow=TRUE), c(1, 2, 3), 3)
bestSubset <- function(item_representations, ratings, n) {
    .Call('_rDppDiversity_bestSubset', PACKAGE = 'rDppDiversity', item_representations, ratings, n)
}

