# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Given item set, item representation vector, and item ratings, find a subset with better relevance-diversity trade-off.
#'
#' @param item_representations Matrix
#' @param ratings Vector
#' @param n int
#'
#' @return DataFrame with 2 columns: id & gain
#' @export
#'
#' @examples
#' library(rDppDiversity)
#' bestSubset(matrix(c(-0.1, -0.15, 0.2, 0.3, -0.2, -0.3), nrow=3, ncol=2, byrow=TRUE), c(1, 2, 3), 3)
bestSubset <- function(item_representations, ratings, n) {
  .Call('_rDppDiversity_bestSubset', PACKAGE = 'rDppDiversity', item_representations, ratings, n)
}

#' Machine learning algorithm to learn item representations maximizing log likelihood under DPP assumption.
#'
#' @param train_data_path string
#' @param emb_size int
#' @param regularization float
#' @param learning_rate float
#' @param neg_sample_cnt int
#' @param epoch int
#'
#' @return List contains: 1) learned item embedding; 2) item names; 3) log likelihood on each training step.
#' @export
#'
#' @examples
#' library(rDppDiversity)
#' data_path=system.file("extdata", "data.txt", package = "rDppDiversity")
#' learnItemEmb(train_data_path=data_path, emb_size=3, regularization=0.1, learning_rate=0.01, neg_sample_cnt=0, epoch=10)
learnItemEmb <- function(train_data_path, emb_size, regularization, learning_rate, neg_sample_cnt, epoch) {
  .Call('_rDppDiversity_learnItemEmb', PACKAGE = 'rDppDiversity', train_data_path, emb_size, regularization, learning_rate, neg_sample_cnt, epoch)
}
